// Copyright (c) 2015 fjz13. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CoreDefines.proto
namespace Medusa.CoreProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Version")]
  public partial class Version : global::ProtoBuf.IExtensible
  {
    public Version() {}
    

    private uint _Major = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Major", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Major
    {
      get { return _Major; }
      set { _Major = value; }
    }

    private uint _Minor = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Minor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Minor
    {
      get { return _Minor; }
      set { _Minor = value; }
    }

    private uint _Build = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Build", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Build
    {
      get { return _Build; }
      set { _Build = value; }
    }

    private uint _Revision = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Revision", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Revision
    {
      get { return _Revision; }
      set { _Revision = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}