// Copyright (c) 2015 fjz13. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FileList.proto
// Note: requires additional types generated from: CoreDefines.proto
namespace Medusa.CoreProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileList")]
  public partial class FileList : global::ProtoBuf.IExtensible
  {
    public FileList() {}
    
    private Medusa.CoreProto.Version _CurVersion;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CurVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Medusa.CoreProto.Version CurVersion
    {
      get { return _CurVersion; }
      set { _CurVersion = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _Dirs = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Dirs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Dirs
    {
      get { return _Dirs; }
    }
  
    private readonly global::System.Collections.Generic.List<Medusa.CoreProto.FileList.FileItem> _Files = new global::System.Collections.Generic.List<Medusa.CoreProto.FileList.FileItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Files", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Medusa.CoreProto.FileList.FileItem> Files
    {
      get { return _Files; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileCoder")]
  public partial class FileCoder : global::ProtoBuf.IExtensible
  {
    public FileCoder() {}
    
    private Medusa.CoreProto.FileList.FileCoder.FileCoderType _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Medusa.CoreProto.FileList.FileCoder.FileCoderType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private uint _Info = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Info", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Info
    {
      get { return _Info; }
      set { _Info = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"FileCoderType")]
    public enum FileCoderType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LZMAEncoder", Value=1)]
      LZMAEncoder = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XOREncoder", Value=2)]
      XOREncoder = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LZMADecoder", Value=101)]
      LZMADecoder = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XORDecoder", Value=102)]
      XORDecoder = 102
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileItem")]
  public partial class FileItem : global::ProtoBuf.IExtensible
  {
    public FileItem() {}
    
    private uint _FileId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FileId
    {
      get { return _FileId; }
      set { _FileId = value; }
    }
    private int _DirIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DirIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DirIndex
    {
      get { return _DirIndex; }
      set { _DirIndex = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _MD5;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"MD5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MD5
    {
      get { return _MD5; }
      set { _MD5 = value; }
    }
    private readonly global::System.Collections.Generic.List<Medusa.CoreProto.FileList.FileCoder> _Coders = new global::System.Collections.Generic.List<Medusa.CoreProto.FileList.FileCoder>();
    [global::ProtoBuf.ProtoMember(5, Name=@"Coders", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Medusa.CoreProto.FileList.FileCoder> Coders
    {
      get { return _Coders; }
    }
  

    private string _OriginalName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"OriginalName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OriginalName
    {
      get { return _OriginalName; }
      set { _OriginalName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}