// Copyright (c) 2015 fjz13. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FileCache.proto
// Note: requires additional types generated from: Geometry.proto
namespace Medusa.CoreProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileCacheItem")]
  public partial class FileCacheItem : global::ProtoBuf.IExtensible
  {
    public FileCacheItem() {}
    
    private string _path;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private string _md5;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"md5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string md5
    {
      get { return _md5; }
      set { _md5 = value; }
    }

    private Medusa.CoreProto.RectU _TextureRect = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TextureRect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Medusa.CoreProto.RectU TextureRect
    {
      get { return _TextureRect; }
      set { _TextureRect = value; }
    }

    private Medusa.CoreProto.PointU _Offset = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Medusa.CoreProto.PointU Offset
    {
      get { return _Offset; }
      set { _Offset = value; }
    }
    private string _OriginalName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"OriginalName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OriginalName
    {
      get { return _OriginalName; }
      set { _OriginalName = value; }
    }
    private uint _Operation;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Operation
    {
      get { return _Operation; }
      set { _Operation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileCache")]
  public partial class FileCache : global::ProtoBuf.IExtensible
  {
    public FileCache() {}
    
    private readonly global::System.Collections.Generic.List<Medusa.CoreProto.FileCacheItem> _items = new global::System.Collections.Generic.List<Medusa.CoreProto.FileCacheItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Medusa.CoreProto.FileCacheItem> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}