// Copyright (c) 2015 fjz13. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FileUpdateList.proto
// Note: requires additional types generated from: CoreDefines.proto
namespace Medusa.CoreProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileUpdateItem")]
  public partial class FileUpdateItem : global::ProtoBuf.IExtensible
  {
    public FileUpdateItem() {}
    
    private string _path;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private string _md5;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"md5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string md5
    {
      get { return _md5; }
      set { _md5 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileUpdateList")]
  public partial class FileUpdateList : global::ProtoBuf.IExtensible
  {
    public FileUpdateList() {}
    
    private Medusa.CoreProto.Version _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Medusa.CoreProto.Version version
    {
      get { return _version; }
      set { _version = value; }
    }
    private readonly global::System.Collections.Generic.List<Medusa.CoreProto.FileUpdateItem> _items = new global::System.Collections.Generic.List<Medusa.CoreProto.FileUpdateItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Medusa.CoreProto.FileUpdateItem> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}