// Copyright (c) 2015 fjz13. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UpdateServer.proto
// Note: requires additional types generated from: CoreDefines.proto
namespace Medusa.CoreProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateServer")]
  public partial class UpdateServer : global::ProtoBuf.IExtensible
  {
    public UpdateServer() {}
    
    private Medusa.CoreProto.UpdateServer.UpdateServerStatus _Status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Medusa.CoreProto.UpdateServer.UpdateServerStatus Status
    {
      get { return _Status; }
      set { _Status = value; }
    }
    private Medusa.CoreProto.Version _MinVersion;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MinVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Medusa.CoreProto.Version MinVersion
    {
      get { return _MinVersion; }
      set { _MinVersion = value; }
    }
    private Medusa.CoreProto.Version _CurVersion;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CurVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Medusa.CoreProto.Version CurVersion
    {
      get { return _CurVersion; }
      set { _CurVersion = value; }
    }
    private string _Description;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"UpdateServerStatus")]
    public enum UpdateServerStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Maintain", Value=1)]
      Maintain = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error", Value=2)]
      Error = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DontUpgrade", Value=3)]
      DontUpgrade = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}